### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by theOrakle** [vinteo/hass-opensprinkler#1]
I'm not sure how to rectify the following error:

2018-09-14 09:32:58 WARNING (MainThread) [homeassistant.loader] You are using a custom component for opensprinkler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2018-09-14 09:32:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component opensprinkler
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homeassistant/config/custom_components/opensprinkler.py", line 47, in setup
    for station in opensprinkler.stations():
  File "/opt/homeassistant/config/custom_components/opensprinkler.py", line 85, in stations
    for i, name in enumerate(response.json()['snames']):
KeyError: 'snames'

**Comment by vinteo** [comment]
Looks like the API is not returning the right response. 

Is the password correct (and MD5'ed) in the config?

What response do you get if you put `http://OPENSPRINKLER_IP/jn?pw=MD5_PASSWORD` into the browser (replace `OPENSPRINKLER_IP` and `MD5_PASSWORD` in your home network?

**Comment by Timple** [comment]
I had the same issue, solved with MD5-ing the password. Easy to overlook in the readme. Maybe replace 
```yaml
    password: <password>
```
```yaml
    password: <md5-password>
```

**Comment by vinteo** [comment]
@Timple thanks for the suggestion!
