### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by ugoogalizer** [vinteo/hass-opensprinkler#11]
Hey Vinteo, 

I have been spinning up your custom component today thanks.  All my garden "switches" have come through well, and they reflect accurately when the sprinklers are on.  However, when I try to trigger them (turn them to state: on) within Home Assistant I get the following error: 

```
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/service.py", line 224, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switch/hass_opensprinkler.py", line 47, in turn_on
    self._station.turn_on(int(float(mins.state)))
AttributeError: 'NoneType' object has no attribute 'state'
```

Is this something I've done wrong with the setup?

**Comment by vinteo** [comment]
When you say "trigger" are you doing it through an automation or script? or just through the Home Assistant UI?

For the error it seems it can't find the "timer" for sprinkler station, there should be one for each station like `input_number.<station_name>_timer`. Can you see these entities in the states list in the developer tools?

**Comment by ugoogalizer** [comment]
Thanks.  I was just manually testing through the GUI.  No I have no
input_number.<station_name>_timer's  dev tools or on GUI main screen. Do I
have to manually create them?

For each station in OpenSprinkler, I see a matching sensor, switch and
binary_sensor that were created automatically, no timers.

I'm at HA 0.80.3.

**Comment by vinteo** [comment]
The timers should be automatically created by the component. Are there any other errors (especially on startup)?

**Comment by ugoogalizer** [comment]
Only the default warnings about using a custom component - the other ERRORS are an ongoing HTML scraper issue I'm working through: 

```
2018-10-25 20:22:39 WARNING (MainThread) [homeassistant.components.http] legacy_api_password support has been enabled. If you don't require it, remove the 'api_password' from your http config. 
2018-10-25 20:22:39 WARNING (MainThread) [homeassistant.loader] You are using a custom component for hass_opensprinkler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant. 
2018-10-25 20:22:40 WARNING (MainThread) [homeassistant.loader] You are using a custom component for binary_sensor.hass_opensprinkler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant. 
2018-10-25 20:22:40 WARNING (MainThread) [homeassistant.loader] You are using a custom component for scene.hass_opensprinkler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant. 
2018-10-25 20:22:40 ERROR (SyncWorker_30) [homeassistant.components.sensor.scrape] Unable to extract data from HTML 
2018-10-25 20:22:40 ERROR (SyncWorker_4) [homeassistant.components.sensor.scrape] Unable to extract data from HTML 
2018-10-25 20:22:40 WARNING (MainThread) [homeassistant.loader] You are using a custom component for sensor.hass_opensprinkler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant. 
2018-10-25 20:22:45 WARNING (MainThread) [homeassistant.loader] You are using a custom component for switch.hass_opensprinkler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant. 
2018-10-25 20:23:11 ERROR (SyncWorker_29) [homeassistant.components.sensor.scrape] Unable to extract data from HTML 
2018-10-25 20:23:11 ERROR (SyncWorker_15) [homeassistant.components.sensor.scrape] Unable to extract data from HTML 
2018-10-25 20:23:42 ERROR (SyncWorker_3) [homeassistant.components.sensor.scrape] Unable to extract data from HTML 
2018-10-25 20:23:42 ERROR (SyncWorker_26) [homeassistant.components.sensor.scrape] Unable to extract data from HTML
```

**Comment by vinteo** [comment]
Hmm that's pretty weird. May I ask what your station names are? Are there any special characters or spaces? 

You could try create them manually as well and see if the switches will work then. The `input_number` holds the number of minutes that the station should run for when turned on. And as mentioned it should be named `input_number.<station_name>_timer` where station name should be the same as the `sensor.<station_name>`

**Comment by ugoogalizer** [comment]
Definitely a good idea thanks! 

The names of my stations are summarised by the binary sensors created: 

```
binary_sensor.back_camelias 	 	off 	friendly_name: Back Camelias
binary_sensor.butterfly_garden 	 	off 	friendly_name: Butterfly Garden
binary_sensor.front_garage_garden 	off 	friendly_name: Front Garage Garden
binary_sensor.front_gardens 	 	off 	friendly_name: Front Gardens
binary_sensor.front_lawn 	 	off 	friendly_name: Front Lawn
binary_sensor.long_south_garden 	off 	friendly_name: Long South Garden
binary_sensor.side_rose_garden 	 	off 	friendly_name: Side Rose Garden
binary_sensor.vege_patch_1  		off 	friendly_name: Vege Patch 1
```
And as you suggested, manually creating the triggers did fix the issue, so my immediate needs are solved thanks. I can now turn on the sprinkler stations from Home Assistant.  However, I don't know why the timers aren't automatically created sorry - happy to keep debuging if you're interested.

Manual creation code: 


```
  back_camelias_timer:
    min: 1
    max: 30
    step: 1
    mode: slider
  butterfly_garden_timer:
    min: 1
    max: 30
    step: 1
    mode: slider
  front_garage_garden_timer:
    min: 1
    max: 30
    step: 1
    mode: slider
  front_gardens_timer:
    min: 1
    max: 30
    step: 1
    mode: slider
  front_lawn_timer:
    min: 1
    max: 30
    step: 1
    mode: slider
  long_south_garden_timer:
    min: 1
    max: 30
    step: 1
    mode: slider
  side_rose_garden_timer:
    min: 1
    max: 30
    step: 1
    mode: slider
  vege_patch_1_timer:
    min: 1
    max: 30
    step: 1
    mode: slider
```

**Comment by ugoogalizer** [comment]
Also note, like BrettWa in #12 , I am also running Home Assistant within a Docker container.  I also updated to your latest code, and had no difference in experience.

**Comment by Timple** [comment]
I am also using docker and I also don't have any timers of sliders created automatically. 
Switches and binary_sensors work.

**Comment by vinteo** [comment]
Looks like docker container may be the issue as I use hass.io. But isn't that in docker container as well? I wonder whats the difference between the two.

**Comment by sgruby** [comment]
Same issue for me and I'm running hass.io, so I think the docker thing is a red herring. I'm using Lovelace and just added the switch entities to a card, toggled one zone and got this error.

**Comment by vinteo** [comment]
So it seems that if you have any input_number entities in your config, the input_number entities will not be setup automatically and have to be setup manually. 

Please refer to the trouble shooting guide in the README on how to do this.

Will close this issue now
