### ISSUE TITLE
last_reboot_time spamming logs

### ISSUE THREAD

**Issue by Gibby** [vinteo/hass-opensprinkler#120]
On 0.112.4 and 1.0.7 of the plugin, I see this in my log file about every 5 seconds.

`2020-07-14 00:56:15 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 111, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 290, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 317, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/opensprinkler/switch.py", line 104, in device_state_attributes
    timestamp = getattr(controller, attr)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 900, in last_reboot_time
    return self._timestamp_to_utc(self._get_variable("lupt"))
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 343, in _timestamp_to_utc
    return timestamp if timestamp == 0 else timestamp - offset
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
`

**Comment by prndlrm** [comment]
I have the same problem. My log was growing to 20MB overnight. I uninstalled the integration for now to get it to stop.

**Comment by vinteo** [comment]
Looks like firmware 2.1.7 and below does not have this property. Fix incoming: https://github.com/vinteo/py-opensprinkler/pull/49

**Comment by vinteo** [comment]
Please try upgrading to 1.0.8

**Comment by Gibby** [comment]
@vinteo thanks, working for me
