### ISSUE TITLE
Sensors don't reconnect after opensprinkler reconnects to WiFi

### ISSUE THREAD

**Issue by cyclemycity** [vinteo/hass-opensprinkler#17]
Vinteo,

Thanks for writing this component, it is fantastic, but I do have one problem I'm wondering if you can help with...

My open sprinkley Raspberry Pi has been dropping off my network every few days. Mysterious, and I haven't found out why, but it does reconnect. Unfortunately once hass-opensprinkler's sensor fails to find it the first time it never seems to be able to find it when it has reconnected.

When Hass last booted Open Sprinkler was also online and the sensors worked, and the states changed as sprinklers came on and off, but today Open Sprinkler disappears from teh WiFi for an hour and has now come back on. I can access the station information with http://192.168.1.190:8080/js?pw=[my-MD5-Password] and get the json back, but Hass.io doesn't seem to be able to. My error is extensive but is basically just "Host is Unreachable", and is copied below for information.

Is this normal or should hass-opensprinkler be able to reconnect when open sprinkler re-joins the WiFi?

Thanks,
Matthew

```
Update for switch.vertical_garden fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x6884ecf0>: Failed to establish a new connection: [Errno 113] Host is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.190', port=8080): Max retries exceeded with url: /js?pw=[my-MD5-Password] (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6884ecf0>: Failed to establish a new connection: [Errno 113] Host is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hass_opensprinkler.py", line 155, in status
    response = requests.get(url, timeout=10)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.190', port=8080): Max retries exceeded with url: /js?pw=[my-MD5-Password] (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x6884ecf0>: Failed to establish a new connection: [Errno 113] Host is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 315, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/switch/hass_opensprinkler.py", line 42, in update
    self._is_on = self._station.status()
  File "/config/custom_components/hass_opensprinkler.py", line 157, in status
    _LOGGER.error("No route to device '%s'", self._resource)
AttributeError: 'OpensprinklerStation' object has no attribute '_resource'
```

**Comment by vinteo** [comment]
The way the component works is that it setups the sensors/switches/scenes on hass load/start. So while it is starting and OS is not available the sensors will not be there.

But once the sensors etc are setup and if OS drops out and come back it should pick it up again. So if this is the case (sensors already setup) for yours, then to answer your question, I don't think it is normal. But I have not really tested this scenario. Maybe you can test it and let me know.

However if it was down for an hour, maybe hass has an internal thing that stops checking after a while.

**Comment by cyclemycity** [comment]
Well, after over 4 hours they have now magically reconnected...? I don't know what would have changed in that time, but 20 minutes ago the errors stopped and the sensors are reconnected/updating with irrigation changes. It 'may' have coincided with the end of one of my programs, but not with the cycling of the valve as that program runs one valve 4 times a day and the network interruption occurred in the middle of the second cycle, the 3rd cycle ran but HA could't tell and the 4th cycle ran, roughly after that ended (or probably just before) the sensors came back.

Anyway, I guess it tries to reconnect broken sensors and just took 4 hours in this case.

Thanks,
Matthew
