### ISSUE TITLE
Check return codes 

### ISSUE THREAD

**Issue by Pocke01** [vinteo/hass-opensprinkler#19]
Hi, 

Been looking for a way to integrate my open sprinkler in HA! So big thanks for doing it!!

But I have a small suggestion.

Add some fault handeling with checking the return codes from OS. 
I had a problem with wrong password but it took some digging to figure it out, cause the error was:
```Log Details (ERROR)
Wed Mar 27 2019 13:06:40 GMT+0100 (CET)

Error during setup of component hass_opensprinkler
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 154, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_opensprinkler/__init__.py", line 51, in setup
    for station in opensprinkler.stations():
  File "/config/custom_components/hass_opensprinkler/__init__.py", line 96, in stations
    for i, name in enumerate(response.json()['snames']):
KeyError: 'snames'```

I had to do a curl on the api to see that I got a {"result":2}. 
Had to check the api documentation what is meant, and it said Unauthorized

The problem was with my password hash that I forgot to remove newline when I created it. 

And for the sliders, that I saw there was some issues on, maybe you can check out this:
https://github.com/thomasloven/lovelace-slider-entity-row

Keep up the good work!!

**Comment by vinteo** [comment]
yup, always good to have some proper error handling

**Comment by vinteo** [comment]
This is now part of the `pyopensprinkler` library being used
