### ISSUE TITLE
constant error 

### ISSUE THREAD

**Issue by madrose** [vinteo/hass-opensprinkler#22]
Hi,
I have been running this custom component for a while now and it working, however, the HA log is filled with the following error:

> May 17 21:14:07 tinkerboard hass[3613]: Traceback (most recent call last):
May 17 21:14:07 tinkerboard hass[3613]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
May 17 21:14:07 tinkerboard hass[3613]:     await self.async_device_update()
May 17 21:14:07 tinkerboard hass[3613]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
May 17 21:14:07 tinkerboard hass[3613]:     await self.hass.async_add_executor_job(self.update)
May 17 21:14:07 tinkerboard hass[3613]:   File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
May 17 21:14:07 tinkerboard hass[3613]:     yield self  # This tells Task to wait for completion.
May 17 21:14:07 tinkerboard hass[3613]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
May 17 21:14:07 tinkerboard hass[3613]:     future.result()
May 17 21:14:07 tinkerboard hass[3613]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
May 17 21:14:07 tinkerboard hass[3613]:     raise self._exception
May 17 21:14:07 tinkerboard hass[3613]:   File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
May 17 21:14:07 tinkerboard hass[3613]:     result = self.fn(*self.args, **self.kwargs)
May 17 21:14:07 tinkerboard hass[3613]:   File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
May 17 21:14:07 tinkerboard hass[3613]:     result = method(*args, **kwargs)
May 17 21:14:07 tinkerboard hass[3613]:   File "/home/homeassistant/.homeassistant/custom_components/hass_opensprinkler/binary_sensor.py", line 44, in update
May 17 21:14:07 tinkerboard hass[3613]:     self._is_on = self._station.status()
May 17 21:14:07 tinkerboard hass[3613]:   File "/home/homeassistant/.homeassistant/custom_components/hass_opensprinkler/__init__.py", line 181, in status
May 17 21:14:07 tinkerboard hass[3613]:     response = requests.get(url, timeout=10)
May 17 21:14:07 tinkerboard hass[3613]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/api.py", line 75, in get
May 17 21:14:07 tinkerboard hass[3613]:     return request('get', url, params=params, **kwargs)
May 17 21:14:07 tinkerboard hass[3613]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/api.py", line 60, in request
May 17 21:14:07 tinkerboard hass[3613]:     return session.request(method=method, url=url, **kwargs)
May 17 21:14:07 tinkerboard hass[3613]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/sessions.py", line 533, in request
May 17 21:14:07 tinkerboard hass[3613]:     resp = self.send(prep, **send_kwargs)
May 17 21:14:07 tinkerboard hass[3613]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/sessions.py", line 646, in send
May 17 21:14:07 tinkerboard hass[3613]:     r = adapter.send(request, **kwargs)
May 17 21:14:07 tinkerboard hass[3613]:   File "/srv/homeassistant/lib/python3.5/site-packages/requests/adapters.py", line 529, in send
May 17 21:14:07 tinkerboard hass[3613]:     raise ReadTimeout(e, request=request)
May 17 21:14:07 tinkerboard hass[3613]: requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.xx.xx', port=xxxx): Read timed out. (read timeout=10)

![image](https://user-images.githubusercontent.com/6616792/57956802-458d4c80-790b-11e9-8bca-7adbf63fef11.png)

The frontend of HA is showing the results as it should. I cannot complain but I was wondering if I have something configure wrongly. It seems silly but I cannot just ignore the error.

**Comment by vinteo** [comment]
Feels like a connection issue.

How often does the logs appear? It is appearing at regular times or randomly?
How strong is the WiFi signal to your opensprinkler device? Are there any dropouts? 

If you haven't already try setting a static IP for your opensprinkler device using DHCP. Check the WiFi signals and maybe change WifFi channels.

**Comment by madrose** [comment]
I have tested the connection to the opensprinkler board, and I tested with a different Wifi link solutions, However the error did not go away. the board has fixed iP configured and i can access via browser anytime with no issue.
![image](https://user-images.githubusercontent.com/6616792/57966209-384e7d00-7960-11e9-89a0-ff8d7012989c.png)
![image](https://user-images.githubusercontent.com/6616792/57966218-603de080-7960-11e9-8b72-dab796749294.png)

**Comment by vinteo** [comment]
Does the error only happen on `back_2` or all the stations? Is that station setup differently than the others?

I have never seen that error but I get the warning sometimes, especially on startup

**Comment by madrose** [comment]
this is affecting all stations, i just took a sample image.
I am upgrading the Pi and some other hardware I am using. I will monitor this and revert back with any update.

**Comment by madrose** [comment]
still getting random errors:
![image](https://user-images.githubusercontent.com/6616792/57970148-043e8080-798f-11e9-8a4d-7d81e4ceb233.png)
![image](https://user-images.githubusercontent.com/6616792/57970164-33ed8880-798f-11e9-8acf-ba6bf5cf80f2.png)

**Comment by Pocke01** [comment]
Im getting the same errors on all sensors.   
My Opensprinkler is using Ethernet, and I have checked that I do not have any pocketless or anything between hass and OS.     Hass is running on an Nuc.

**Comment by madrose** [comment]
I have upgraded the connection to my opensprinkler system and ensure the connectivity. tried accessing directly using the browser with no issues at all, however in HA the error keep coming back.

**Comment by Kdemontf** [comment]
I see this is old, but open. I have the same issue I believe on HA  0.104.2, and recent versions. Running in Linux venv, OS V 2.3 - AC firmware 2.1.9. Direct network connection, static IP. The API responds consistantly to rest calls from browser, in 2 seconds or less. I see this in the logs:
``
Updating hass_opensprinkler binary_sensor took longer than the scheduled update interval 0:00:05
11:30 AM helpers/entity_platform.py (WARNING) - message first occurred at January 22, 2020, 8:51 AM and shows up 4400 times
Updating hass_opensprinkler switch took longer than the scheduled update interval 0:00:05
11:30 AM helpers/entity_platform.py (WARNING) - message first occurred at January 22, 2020, 8:51 AM and shows up 3578 times
Updating hass_opensprinkler sensor took longer than the scheduled update interval 0:00:10
11:30 AM helpers/entity_platform.py (WARNING) - message first occurred at January 22, 2020, 8:51 AM and shows up 3610 times
``

Note, I changed the update interval for the sensor, as you can see that did not resolve. It is timing out I think, not sure why. I can control all stations, but system is slow to report status.  Any suggestions on troubleshooting this? I would like to keep it, but need to resolve. Thanks

**Comment by Kdemontf** [comment]
More verbose error messages, is this an ssl error?
``
2020-01-23 12:01:54 WARNING (MainThread) [homeassistant.components.switch] Updating hass_opensprinkler switch took longer than the scheduled update interval 0:00:05
2020-01-23 12:01:54 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating hass_opensprinkler binary_sensor took longer than the scheduled update interval 0:00:05
2020-01-23 12:01:54 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.grass_driveway_n_west fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 288, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: 
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/srv/homeassistant/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 288, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x00À\x00@\x00\x00.1 200 OK\r\n'))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/hass_opensprinkler/__init__.py", line 215, in status
    response = requests.get(url, timeout=10)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x00À\x00@\x00\x00.1 200 OK\r\n'))

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/hass_opensprinkler/switch.py", line 42, in update
    self._is_on = self._station.status()
  File "/home/homeassistant/.homeassistant/custom_components/hass_opensprinkler/__init__.py", line 218, in status
    _LOGGER.error("No route to device '%s'", self._resource)
AttributeError: 'OpensprinklerStation' object has no attribute '_resource'
``

**Comment by vinteo** [comment]
Please try the new release, if there is any issues please create a new issue.
