### ISSUE TITLE
Issue on 0.95.0

### ISSUE THREAD

**Issue by Jemjem787** [vinteo/hass-opensprinkler#26]
When i try to run this on the newest version, the component doesn't even load, i get an error stating

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_opensprinkler/__init__.py", line 55, in setup
    for station in opensprinkler.stations():
  File "/config/custom_components/hass_opensprinkler/__init__.py", line 118, in stations
    for i, name in enumerate(response.json()['snames']):
KeyError: 'snames'

**Comment by vinteo** [comment]
I haven't upgraded HA yet, will take look.

**Comment by vinteo** [comment]
@Jemjem787 it still works for me with 0.95.0. The errors look like it could be an auth failure. Did it work before the upgrade?

**Comment by Jemjem787** [comment]
Yes, i am unsure what caused the error but it may of been unrelated to the update.
