### ISSUE TITLE
OpenSprinkler Firmware 2.2.0 (2) unexpected error

### ISSUE THREAD

**Issue by Feldermann** [vinteo/hass-opensprinkler#263]
Hi,
After updating OpenSprinklerPi to latest Firmware 2.2.0 (2) App Version 2.3.3 connection does not work anymore.
When I try to establish a new connection in HA I get an "unexpected error":

Logger: custom_components.opensprinkler.config_flow
Source: custom_components/opensprinkler/config_flow.py:45
Integration: OpenSprinkler (documentation, issues)
First occurred: 12:41:26 (1 occurrences)
Last logged: 12:41:26

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/opensprinkler/config_flow.py", line 45, in async_step_user
    await controller.refresh()
  File "/usr/local/lib/python3.11/site-packages/pyopensprinkler/__init__.py", line 218, in refresh
    await self._refresh_state()
  File "/usr/local/lib/python3.11/site-packages/pyopensprinkler/__init__.py", line 237, in _refresh_state
    content = await self.request("/ja")
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyopensprinkler/__init__.py", line 145, in request
    content = await self._request_http(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyopensprinkler/__init__.py", line 191, in _request_http
    content = await resp.json(
              ^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 72, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1120, in json
    return loads(stripped.decode(encoding))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 1071: invalid start byte

**Comment by vinteo** [comment]
I think there was an issue with the opensprinkler API with special and accented characters, try renaming your station/programs without those characters
