### ISSUE TITLE
Getting lots of exceptions with latest verstion

### ISSUE THREAD

**Issue by chrismcca** [vinteo/hass-opensprinkler#274]
Updated to latest version of add-in.  Now getting hundreds of the following exceptions in the log.  Is there a way to fix this?

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/opensprinkler/__init__.py", line 268, in state
    return self._get_state()
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opensprinkler/sensor.py", line 281, in _get_state
    return utc_from_timestamp(self._controller.device_time + pt).isoformat()
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

**Comment by curlydingo** [comment]
What version of sprinkler firmware are you running? I suspect it's older than 2.2.0, when the pause feature was introduced.

Still, the integration should handle this more gracefully, I'll add a check to suppress the exceptions.

**Comment by spikeygg** [comment]
> What version of sprinkler firmware are you running? I suspect it's older than 2.2.0, when the pause feature was introduced.
> 
> Still, the integration should handle this more gracefully, I'll add a check to suppress the exceptions.

Thanks! I wasn't even aware there was a new version... I just updated and it seems much more stable. 👍
