### ISSUE TITLE
Everything unavailable in 2024.5.1

### ISSUE THREAD

**Issue by CZonin** [vinteo/hass-opensprinkler#285]
Just updated to 2024.5.1 and the integration is failing to load. The only thing I see in the logs is:

```
This error originated from a custom integration.

Logger: custom_components.opensprinkler
Source: helpers/update_coordinator.py:321
integration: OpenSprinkler (documentation, issues)
First occurred: 6:49:43 PM (17 occurrences)
Last logged: 7:22:00 PM

Timeout fetching OpenSprinkler resource status data
```

Let me know if there's anything else I can provide.

**Comment by vinteo** [comment]
unfortunately it seems my OS device has decided to retire after 6 or so years. Will have to order a new one. Hopefully someone else can confrim for you but just make sure its not a network issue, try restarting the OS device as well if you haven't already

**Comment by CZonin** [comment]
Seems like it is an issue with my controller. I'm stuck in a reboot loop. Factory reset it and still the same issue. Just opened an issue on the OpenSprinkler page. I'll see what happens.

**Comment by Nick-Adams-AU** [comment]
Seems like an issue with the integration and a recent HA update. Here's what I have in my logs:

```Logger: homeassistant.config_entries
Source: config_entries.py:772
First occurred: May 4, 2024 at 8:49:22 AM (7 occurrences)
Last logged: May 4, 2024 at 8:49:24 AM

Error unloading entry OpenSprinkler for select
Error unloading entry OpenSprinkler for sensor
Error unloading entry OpenSprinkler for switch
Error unloading entry OpenSprinkler for text
Error unloading entry OpenSprinkler for time
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 772, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 240, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 200, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!```

**Comment by Sweti934** [comment]
Hei - we now bought also the openSprinkler system. Is this issue still live (and is the development Team also frequently here by any chacne?) ? Just want to know, if this system is well supported (Y) Thanks all!

**Comment by seglo** [comment]
I'm not sure if it's related, but I'm unable to find the integration when I search for it in HACS either.

**Comment by wauswaus** [comment]
I tried uninstalling and re-installing the integration.
I now get the message it cannot connect to the controller. Running Home Assistant 2024.5.5

Log entry:

`2024-06-01 22:00:53.570 ERROR (MainThread) [backoff] Giving up _request_http(...) after 3 tries (pyopensprinkler.OpenSprinklerConnectionError: Cannot connect to controller)
2024-06-01 22:00:53.570 ERROR (MainThread) [custom_components.opensprinkler] Cannot connect to controller
2024-06-01 22:00:53.570 ERROR (MainThread) [custom_components.opensprinkler] Error fetching OpenSprinkler resource status data: Error fetching OpenSprinkler state`

**Comment by EdLeckert** [comment]
> Seems like an issue with the integration and a recent HA update. Here's what I have in my logs:

@Nick-Adams-AU: Did you ever resolve this?

**Comment by EdLeckert** [comment]
> Hei - we now bought also the openSprinkler system. Is this issue still live (and is the development Team also frequently here by any chacne?) ? Just want to know, if this system is well supported (Y) Thanks all!

@Sweti934: My system is solid under HA 2024.5.4. It looks like these are controller and config issues.
