### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 854: invalid continuation byte

### ISSUE THREAD

**Issue by MichaelS75** [vinteo/hass-opensprinkler#308]
Hello everyone,

Since updating to OSPI 2.2.1(0) and restoring it's config I'm faceing following error in Home Assistant:

```
2024-08-29 16:56:02.002 DEBUG (MainThread) [custom_components.opensprinkler] refreshing data
2024-08-29 16:56:02.043 ERROR (MainThread) [custom_components.opensprinkler] Unexpected error fetching OpenSprinkler resource status data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opensprinkler/__init__.py", line 84, in async_update_data
    await controller.refresh()
  File "/usr/local/lib/python3.12/site-packages/pyopensprinkler/__init__.py", line 229, in refresh
    await self._refresh_state()
  File "/usr/local/lib/python3.12/site-packages/pyopensprinkler/__init__.py", line 248, in _refresh_state
    content = await self.request("/ja")
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyopensprinkler/__init__.py", line 145, in request
    content = await self._request_http(url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyopensprinkler/__init__.py", line 202, in _request_http
    content = await resp.json(
              ^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1216, in json
    return loads(stripped.decode(encoding))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 854: invalid continuation byte
2024-08-29 16:56:02.043 DEBUG (MainThread) [custom_components.opensprinkler] Finished fetching OpenSprinkler resource status data in 0.041 seconds (success: False)
```

After the OSPI update I noticed the remark in the hass-opensprinkler readme file "Last tested on OS API 2.2.0 and Home Assistant 2024.2.0" - too late.

Direct browser access to the OSPi URL works fine.

Versions:
Opensprinkler Pi 2.2.1(0) (https://github.com/OpenSprinkler/OpenSprinkler-Firmware/releases)
HASS-Opensprinkler: 1.3.8
HACS: 1.34.0
HA Core 2024.8.3
Supervisor 2024.08.0
Operating System 13.1
Frontend 20240809.0

Thanks

**Comment by vinteo** [comment]
See https://github.com/vinteo/hass-opensprinkler/issues/303

**Comment by MichaelS75** [comment]
Thanks, that was exactly the problem:
I had a program that was called "... täglich" (german for "... daily") and the restore routine of the OSPI config messed up the german umlaut.
Renamed it, reloaded the HA integration and everything is fine again.  👍
