### ISSUE TITLE
No longer works in Home Assistant 2024.12 container

### ISSUE THREAD

**Issue by klein1jo** [vinteo/hass-opensprinkler#322]
Running the official Home Assistant container.  Version 2024.12 was recently released which requires Python 3.13.  Integration on longer works.

Setup failed for custom integration 'opensprinkler': Unable to import component: No module named 'pyopensprinkler'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/opensprinkler/__init__.py", line 30, in <module>
    from pyopensprinkler import Controller as OpenSprinkler
ModuleNotFoundError: No module named 'pyopensprinkler'

**Comment by klein1jo** [comment]
Looks like maybe in the switch to Python 3.13 the hass project accidentally removed an include for /config/deps?  That is where the HACS python modules are installed.  I'm using a `podman create` statement to create my hass container.  I added an environment variable to my hass create statement.

`-e PYTHONPATH="$PYTHONPATH:/config/deps"`

After doing that all my HACS installed integrations are working again.  Closing this issue this off as not an issue with this project and opening an issue with the core project.
