### ISSUE TITLE
Error in setup?

### ISSUE THREAD

**Issue by simo26246** [vinteo/hass-opensprinkler#36]
Hi,

I've copied the files into custom_components and get the following issue

2019-11-17 21:45:24 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hass_opensprinkler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-11-17 21:45:24 ERROR (MainThread) [homeassistant.setup] Error during setup of component hass_opensprinkler
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 176, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_opensprinkler/__init__.py", line 55, in setup
    for station in opensprinkler.stations():
  File "/config/custom_components/hass_opensprinkler/__init__.py", line 118, in stations
    for i, name in enumerate(response.json()['snames']):
KeyError: 'snames'

I'm running latest HassIO and opensprinklerpi, so could be something to do with that, but any help would be appreciated?

**Comment by vinteo** [comment]
Hi, check the password you have entered in the config, remember you have to
md5 it

**Comment by idxman01** [comment]
There was actually a structure change in the json response due to supporting two sensors... which did break the home assistant module.  

I’ll have to look at what I changed. It was something like the key name being s1 instead of just ‘s’.  I’m not at a computer right now.

**Comment by vinteo** [comment]
Hi @simo26246 does the latest release fix your issue?

**Comment by simo26246** [comment]
Hey mate, I tried to reply the other day but it didn't work. I hadn't md5'd
the password - did that then my issue resolved. Thanks!

**Comment by vinteo** [comment]
Great! Closing this issue
