### ISSUE TITLE
Switch stop working ( Fail to call service switch/turn_on .... )

### ISSUE THREAD

**Issue by hmbarbosa** [vinteo/hass-opensprinkler#48]
Hi Vinteo,

When you have a chance are you able please to check below error? All switches stoped... I still have control of open sprinkler but not for switch(Fail to call service switch/turn_on ....) Cheers!!

Logger: homeassistant.components.websocket_api.http.connection.139682826209808
Source: custom_components/hass_opensprinkler/switch.py:89 
Integration: websocket_api (documentation, issues) 
First occurred: 1:58:13 PM (3 occurrences) 
Last logged: 1:59:06 PM

'NoneType' object has no attribute 'state'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1232, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/homeassistant/homeassistant/core.py", line 1255, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 412, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 600, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 443, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 625, in async_turn_on
    await self.hass.async_add_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hass_opensprinkler/switch.py", line 89, in turn_on
    self._station.turn_on(int(float(mins.state)))
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by vinteo** [comment]
you probably added a new input_number entity. Check the troubleshooting section in the readme

**Comment by hmbarbosa** [comment]
Thanks!!!! Sorted now.
