### ISSUE TITLE
Unexpected error for call_service 

### ISSUE THREAD

**Issue by JurajNyiri** [vinteo/hass-opensprinkler#93]
Hello,

Today, when my automation ran I got following error:

```
Water front side: Error executing script. Unexpected error for call_service at pos 7: 'result'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 623, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 517, in handle_service
    required_features,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opensprinkler/__init__.py", line 385, in run
    return self._station.run(run_seconds)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/station.py", line 70, in run
    return self._manual_run(params)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/station.py", line 30, in _manual_run
    return content["result"]
KeyError: 'result'
```

My automation:

```
- id: "1588888773428"
  alias: Water front side
  description: ""
  trigger:
    - entity_id: binary_sensor.s05_station_running
      for: 00:00:30
      from: "on"
      platform: state
      to: "off"
  condition:
    - above: "5"
      condition: numeric_state
      entity_id: sensor.daikinap60251_outside_temperature
    - condition: state
      entity_id: input_boolean.automatic_sprinkler_control
      state: "on"
    - condition: state
      entity_id: input_boolean.automatic_watering
      state: "on"
    - condition: state
      entity_id: input_boolean.watering_back
      state: "on"
    - condition: state
      entity_id: binary_sensor.opensprinkler_sensor_1_active
      state: "off"
  action:
    - data:
        entity_id: switch.s02_station_enabled
      service: opensprinkler.stop
    - delay: 00:00:02
    - data:
        entity_id: switch.s01_station_enabled
        run_seconds: 64800
      service: opensprinkler.run
    - delay: 00:00:02
    - data_template:
        entity_id: switch.s04_station_enabled
        run_seconds: "{{ (states('input_number.front_side_watering_time_min') | float * 60) | int }}"
      service: opensprinkler.run
    - delay: 00:00:10
    - data_template:
        entity_id: switch.s04_station_enabled
        run_seconds: "{{ (states('input_number.front_side_watering_time_min') | float * 60) | int }}"
      service: opensprinkler.run
    - delay: 00:00:02
    - data: {}
      entity_id: input_boolean.watering_back
      service: input_boolean.turn_off
```

When I ran the automation again manually trough automation.trigger it succeeded.

**Home Assistant 0.110.4
hass-opensprinkler v1.0.1
App version: 2.1.10
Firmware: 2.1.9
Hardware: OSPI on Rpi 3**

Note: I know I have the run command there twice and a lot of delays. This is because previously before 1.0.0 they were needed as it was not reliable. I need to test how it works nowadays and whether I can trust one run command or/and can execute multiple commands at the same time.

**Comment by vinteo** [comment]
Based on the error, I think the request was sent to the OS but the response was malformed. Did all the stations run anyway? Do you know for which command did the particular error occur for?

If they did, maybe we will just log a warning, if it didn't maybe we implement some sort of retry.

BTW that's a pretty complex automation, always interesting to see other people's use cases.

**Comment by vinteo** [comment]
Also looks like your use case is another vote for this: https://github.com/vinteo/hass-opensprinkler/issues/78

So multiple stations can be run with a single call

**Comment by travisghansen** [comment]
Yeah, that one will help automation substantially. With that one in place we should be able to handle some pretty crazy use cases.

**Comment by travisghansen** [comment]
What sort of history do you have running this kind of automation and how successful has it been in the past (in terms of submitting via the api)? This seems like it was simply an intermittent connectivity issue but maybe not..

**Comment by JurajNyiri** [comment]
The stations did not run, that's how I noticed that something went wrong with the automation.

No idea which command caused the error, unfortunately... I wasn't able to replicate it yet and it's impossible to tell from the logs.

Yes running multiple stations with a single call would be **really** awesome.

What I am doing is basically using OpenSprinkler as a relay and doing all the logic through the Home Assistant. 

To add a little more background, I have the following stations:
S01: Master valve, opens water to all the other valves
S02: Drain valve, when opened, all the water goes back to the well
S03, S06: Water sockets, should be always on unless its freezing
S04, S05: Sprinklers for front and back of the yard.

I have many automations which make sure that:
- S02 (The drain) is opened when it's going to be freezing using local and remote sensors, this also closes all the other ones 
Unless it's freezing:
- S03, S06 (sockets) should be opened always (unless the drain is opened)
- Whenever S03-S06 (sockets and sprinklers) are turned on, S01 (Master) should be as well
- When S04 or S06 finishes (sprinklers), everything else is closed and S02 (drain) is opened for a couple of seconds. This makes sure that sprinklers close really fast due to pressure change, looks nicer.
- Back sprinklers (S06) water after sunset or sunrise for a period set in the UI, unless it was raining (rain sensor)
- Front sprinklers (S04) water 30 seconds after back sprinklers turn off for a period set in the UI, unless it was raining (rain sensor)

All the automations have delays in them to make sure all the commands succeed. Previously when running without delays some commands would not go through sometimes.

Maybe off-topic question but I noticed it can take up to 30 seconds for changes to show up in Home Assistant. I can see the default scan interval is 5, which is weird. On the previous version it was a lot faster, realistically I think about those 5 seconds.

**Comment by vinteo** [comment]
Please keep an eye on it (I am sure you will) and see if happens again.

The scan interval is a thing I missed, its actually 15 seconds right now, will change it back to 5 secs in the next release

**Comment by JurajNyiri** [comment]
Hello, today my automation didn't run again because of a different error:

```
Logger: homeassistant.components.automation
Source: custom_components/opensprinkler/__init__.py:383
Integration: Automation (documentation, issues)
First occurred: 4:52:14 AM (1 occurrences)
Last logged: 4:52:14 AM

Water back side: Error executing script. Unexpected error for call_service at pos 5: Idle
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 623, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 517, in handle_service
    required_features,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opensprinkler/__init__.py", line 383, in run
    return self._station.run(run_seconds)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/station.py", line 70, in run
    return self._manual_run(params)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/station.py", line 29, in _manual_run
    (_, content) = self._controller.request("/cm", params)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 96, in request
    self.refresh()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 130, in refresh
    self._refresh_state()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 142, in _refresh_state
    (_, content) = self.request("/ja")
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 79, in request
    (resp, content) = self.request_http(url)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 104, in request_http
    (resp, content) = self._http_client.request(url, "GET", headers=headers)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1994, in request
    cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1589, in _conn_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1334, in getresponse
    raise ResponseNotReady(self.__state)
http.client.ResponseNotReady: Idle
```

One of my other automation also didn't run because of another error

```
Logger: homeassistant.components.automation
Source: custom_components/opensprinkler/__init__.py:383
Integration: Automation (documentation, issues)
First occurred: June 2, 2020, 11:00:13 PM (2 occurrences)
Last logged: 3:00:21 AM

Turn on water sockets when temperature above limit: Error executing script. Unexpected error for call_service at pos 3: exceptions must derive from BaseException
Turn on water sockets when temperature above limit: Error executing script. Unexpected error for call_service at pos 7: exceptions must derive from BaseException
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1589, in _conn_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 288, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ,"stations":{"masop":[255],"masop2":[0],"ignore_rain":[0],"ignore_sn1":[0],"ignore_sn2":[0],"stn_dis":[0],"stn_seq":[0],"stn_spe":[0],"snames":["S01","S02","S03","S04","S05","S06","S07","S08"],"maxlen":32}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 623, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 517, in handle_service
    required_features,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opensprinkler/__init__.py", line 383, in run
    return self._station.run(run_seconds)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/station.py", line 70, in run
    return self._manual_run(params)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/station.py", line 29, in _manual_run
    (_, content) = self._controller.request("/cm", params)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 96, in request
    self.refresh()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 130, in refresh
    self._refresh_state()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 142, in _refresh_state
    (_, content) = self.request("/ja")
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 79, in request
    (resp, content) = self.request_http(url)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 104, in request_http
    (resp, content) = self._http_client.request(url, "GET", headers=headers)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1994, in request
    cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1598, in _conn_request
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1236, in connect
    raise socket_err
TypeError: exceptions must derive from BaseException
```

**Comment by JurajNyiri** [comment]
Another type of error message:

```
Logger: homeassistant.components.automation
Source: custom_components/opensprinkler/__init__.py:387
Integration: Automation (documentation, issues)
First occurred: 10:09:04 AM (1 occurrences)
Last logged: 10:09:04 AM

Sprinkler off: Error executing script. Unexpected error for call_service at pos 5: exceptions must derive from BaseException
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1589, in _conn_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 288, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: Content-Type: application/json


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 153, in _async_step
    self, f"_async_{cv.determine_script_action(self._action)}_step"
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 623, in _async_call_service_step
    *self._prep_call_service_step(), blocking=True, context=self._context
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 517, in handle_service
    required_features,
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/opensprinkler/__init__.py", line 387, in stop
    return self._station.stop()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/station.py", line 75, in stop
    return self._manual_run(params)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/station.py", line 29, in _manual_run
    (_, content) = self._controller.request("/cm", params)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 96, in request
    self.refresh()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 130, in refresh
    self._refresh_state()
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 142, in _refresh_state
    (_, content) = self.request("/ja")
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 79, in request
    (resp, content) = self.request_http(url)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyopensprinkler/__init__.py", line 104, in request_http
    (resp, content) = self._http_client.request(url, "GET", headers=headers)
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1994, in request
    cachekey,
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1598, in _conn_request
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/httplib2/__init__.py", line 1236, in connect
    raise socket_err
TypeError: exceptions must derive from BaseException
```

**Comment by vinteo** [comment]
does this still happen?

**Comment by JurajNyiri** [comment]
No all is good now thank you!
